app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	$conferences = App\Conference::all();
    return view('welcome', compact('conferences'));
});


Route::controller('/registration', 'RegistrationController');

Route::group(['middleware' => ['auth']], function () {
    Route::controller('/booking', 'BookingController');
});

Route::group(['middleware' => ['auth.basic', 'is.admin']], function () {
    Route::controller('/admin', 'AdminController');
});

app/Conference.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Conference extends Model
{

    protected $guarded = ['id'];

    public function workshops()
    {
        return $this->hasMany('App\Workshop');
    }

    /**
     * Verify is there is a workshop for this day for this conference
     * @param  int  $weekday Week Day (1=Monday)
     * @return boolean
     */
    public function hasWorkshopOnDay($weekday)
    {
        return $this->workshops()->where('weekday', $weekday)->count() > 0;
    }

    /**
     * Get workshop on the specified day or null
     * @param  int  $weekday Week Day (1=Monday)
     * @return App\Workshop|null
     */
    public function getWorkshopOnDay($weekday)
    {
        return $this->workshops()->where('weekday', $weekday)->first();
    }

    /**
     * Format time to HH:MM
     * @param  string $value Time to be transform
     * @return string        Formatted time
     */
    protected function formatTime($value)
    {
        return date('H:i', strtotime($value));
    }

    public function getTimeStartAttribute($value)
    {
        return $this->formatTime($value);
    }

    public function getTimeEndAttribute($value)
    {
        return $this->formatTime($value);
    }
}

resources/views/admin/index.blade.php
@extends('layouts.master')

@section('content')
<h1>Administration</h1>
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif


<table class="border">
	<thead>
		<th>Day</th>
		<th>Session</th>
		<th>Booking Number</th>
		<th>Attendees</th>
		<th>Status</th>
		<th>Action [Confirm - Deny - Reschedule]</th>
	</thead>
	<tbody>
		@foreach ($attendees as $attendee)
			<tr>
				<td>{{ $attendee->workshop->humanWeekDay() }}</td>
				<td>{{ $attendee->workshop->conference->name }} {{ $attendee->workshop->conference->time_start }} {{ $attendee->workshop->conference->time_end }}</td>
				<td>{{ $attendee->bookingNumber() }}</td>
				<td>{{ $attendee->name }}</td>
				<td>{{ $attendee->status }}</td>
				<td>
					<label><input type="radio" name="action[{{ $attendee->id }}]" value="confirm" /> Confirm</label>
					<label><input type="radio" name="action[{{ $attendee->id }}]" value="deny" /> Deny</label>
					<label><input type="radio" name="action[{{ $attendee->id }}]" value="reschedule" /> Reschedule</label>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>

<a href="{{ action('AdminController@getCsv') }}">Export CSV</a>
@endsection